#!/bin/sh 
rfkill unblock bluetooth
sleep 1
hciconfig hci0 down
sleep 1
hciconfig hci0 up
sleep 1


#hcitool scan

COMM_VSIDO=rfcomm75


echo "${1}"
mkdir -p /opt/vsido/usr/etc/
touch /opt/vsido/usr/etc/bt.bind
killall rfcomm
if [ "" = "${1}" ] ; then
	address=`cat /opt/vsido/usr/etc/bt.bind`
	rfcomm  connect hci0 ${address} &
else 
	rfcomm  connect hci0 ${1}  &
	echo "${1}" >/opt/vsido/usr/etc/bt.bind
fi
sleep 10
ln -sf /dev/rfcomm0 /dev/${COMM_VSIDO}
sync
